# 행렬
- 행렬은 2차원으로 구성된 숫자의 집합이며, 리스트의 리스트로 표현할 수 있다.
- 리스트 안의 리스트들은 행렬의 행을 나타내며 모두 같은 길이를 가지게 된다.

In [1]:
from typing import List


Vector = List[float]
Matrix = List[List[float]]

A = [[1, 2, 3],
    [4, 5, 6]]

B = [[1, 2],
    [3, 4],
    [5, 6]]

- 행렬 A는 len(A)개의 행과 len(A[0]) 개의 열로 구성 된다.

In [2]:
from typing import Tuple

def shape(A: Matrix) -> Tuple[int, int]:
    """(열의 개수, 행의 개수)"""
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0 # 첫 번재 행의 원소의 개수
    return num_rows, num_cols

assert shape([[1, 2, 3], [4, 5, 6]]) == (2, 3)

- 행렬이 n 개의 행과 k개의 열로 구성되어 있다면 n x k 행렬이라고 부른다.

In [3]:
# i번째 행을 반환
def get_row(A: Matrix, i: int)-> Vector:
    """A의 i번째 행을 반환"""
    return A[i]

In [4]:
# j번째 열을 반환
def get_colum(A: Matrix, j: int)-> Vector:
    """A의 j번재 열을 반환"""
    return [A_i[j] for A_i in A]

### 단위 행렬
- 대각선의 원소는 1이고 나머지 원소는 0인 행렬

In [5]:
from typing import Callable


def make_matrix(num_rows: int, num_cols: int, entry_fn: Callable[[int, int], float]) -> Matrix:
    """(i, j) 번째 원소가 entr_fn(i, j)인 num_rows x num_cols 리스트를 반환"""
    return [[entry_fn(i, j) for j in range(num_cols)] for i in range(num_rows)]

def identity_matrix(n : int) -> Matrix:
    """nxn 단위 행렬을 반환"""
    return make_matrix(n, n, lambda i, j: 1 if i == j else 0)

identity_matrix(5)

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

## 다차원 배열 계산하기

In [6]:
import numpy as np
A = np.arange(1, 5).reshape(2,2)
B = np.arange(5, 9).reshape(2,2)

In [7]:
A.shape, B.shape

((2, 2), (2, 2))

numpy의 dot 함수를 활용하면 행렬의 내적을 구할 수 있다.

In [8]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [9]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

### Shape이 서로 다를 때의 내적 규칙

In [10]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)
A.shape, B.shape

((2, 3), (3, 2))

In [11]:
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [12]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [13]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [14]:
C = np.arange(1, 5).reshape(2, 2)
C.shape

(2, 2)

In [15]:
np.dot(C, A)

array([[ 9, 12, 15],
       [19, 26, 33]])

### 차원수가 다른 경우의 행렬 내적 구하기

In [16]:
A = np.arange(1, 7).reshape(3,2)
B = np.array([7, 8])

A.shape, B.shape

((3, 2), (2,))

In [17]:
np.dot(A, B)

array([23, 53, 83])

In [18]:
## 신경망에서의 행렬 내적

In [19]:
X = np.array([1, 2])
W = np.array([[1, 3, 5],
             [2, 4, 6]])

Y = np.dot(X, W)

In [20]:
Y

array([ 5, 11, 17])

In [21]:
X = np.array([1.0, 0.5])
# 1층의 가중치
W1 = np.array([[0.1, 0.3, 0.5],
              [0.2, 0.4, 0.6]])

# 1층의 vusgidemf
B1 = np.array([0.1, 0.2, 0.3])

X.shape, W1.shape, B1.shape

((2,), (2, 3), (3,))

In [22]:
A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [24]:
import numpy as np
A = np.arange(1, 5).reshape(2,2)
B = np.arange(5, 9).reshape(2,2)## 다차원 배열 계산하기

In [25]:
A.shape, B.shape

((2, 2), (2, 2))

numpy의 dot 함수를 활용하면 행렬의 내적을 구할 수 있다.

In [26]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

### Shape이 서로 다를 때의 내적 규칙

In [28]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(1, 7).reshape(3, 2)
A.shape, B.shape

((2, 3), (3, 2))

In [29]:
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [ ]:
np.dot(A, B)

In [ ]:
np.dot(B, A)

In [ ]:
C = np.arange(1, 5).reshape(2, 2)
C.shape

In [ ]:
np.dot(C, A)

### 차원수가 다른 경우의 행렬 내적 구하기

### 차원수가 다른 경우의 행렬 내적 구하기

In [ ]:
### 차원수가 다른 경우의 행렬 내적 구하기